[versions]
spring-boot = "3.2.12"
spring-dependency-management = "1.1.4"
kotlin = "1.9.23"
mybatis-plus = "3.5.11"
jjwt = "0.12.5"
ktlint = "12.1.0"
jacoco = "0.8.11"

[libraries]
# Spring Boot Starters
spring-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-devtools = { module = "org.springframework.boot:spring-boot-devtools" }

# MyBatis Plus
mybatis-plus-boot = { module = "com.baomidou:mybatis-plus-spring-boot3-starter", version.ref = "mybatis-plus" }
mybatis-plus-jsqlparser = { module = "com.baomidou:mybatis-plus-jsqlparser", version.ref = "mybatis-plus" }

# Database
mysql-connector = { module = "com.mysql:mysql-connector-j" }
flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql" }

# JWT
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

# Lombok
lombok = { module = "org.projectlombok:lombok" }

# Test
assertj = { module = "org.assertj:assertj-core" }
security-test = { module = "org.springframework.security:spring-security-test" }
h2 = { module = "com.h2database:h2" }


[bundles]
spring-basic = ["spring-web", "spring-security", "spring-validation", "spring-data-redis", "spring-actuator"]
jjwt = ["jjwt-api", "jjwt-impl", "jjwt-jackson"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
